config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>

<%= link_to "Hello", say_hello_path %>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>

<p>
  It is now <%= @time %>
</p>

+1 hour: <%= 1.hour.from_now.localtime %>

<p>
  Time to say <%= link_to "Goodbye", say_goodbye_path %>!
</p>

List of files:
<% @files.each do |file| %>
  <ul>
    <li><%= file %></li>
  </ul>
<% end %>